/*
 Copyright &copy; 2013 Alja? Pintar
 @license http://opensource.org/licenses/MIT MIT license

*/
(function(b){b.fn.shinyImage=function(k){var a=b.extend({height:b(this).height(),width:b(this).width(),customImage:b(this).attr("src"),opacity:19,thickness:92,colorFill:{r:255,g:255,b:255},FPS:30,angle:130,speed:100,delay:2,type:1,loop:!0,doubleside:!1,customEffect:"",_currentPosition:b(this).height(),_currentDelay:0,_waiting:!0,_considerAlpha:!0,_update:!0},k);b(this).replaceWith("<canvas id='c'></canvas>");b("canvas").attr({width:a.width,height:a.height});b("canvas").css({width:a.width,height:a.height});
var g=b("canvas").get(0),c=g.getContext("2d");(function(){setInterval(function(){if(a._update){c.clearRect(0,0,a.width,a.height);var d=new Image;d.src=a.customImage;c.drawImage(d,0,0,a.width,a.height);var b,l;try{b=c.getImageData(0,0,a.width,a.height),l=b.data}catch(k){}if(a._waiting)a._currentDelay-=1/a.FPS,0>a._currentDelay&&(a._currentDelay=a.delay,a.loop||(a._update=!1),a._waiting=!1);else{c.save();c.translate(a.width/2,a.height/2);c.rotate(a.angle*Math.PI/180);c.translate(-a.width/2,-a.height/
2);a._currentPosition-=0.3*a.speed;d=-0.5*g.width;b=a._currentPosition;var h=2*g.width,f=a.thickness;if("undefined"!==a.customEffect&&""!==a.customEffect){var e=new Image;e.src=a.customEffect;c.drawImage(e,d,b,h,f)}else e=c.createLinearGradient(d,b,d,parseInt(b)+parseInt(f)),e.addColorStop(0,"rgba("+a.colorFill.r+","+a.colorFill.g+","+a.colorFill.b+","+parseInt(a.opacity)/100+")"),e.addColorStop(1,"rgba("+a.colorFill.r+","+a.colorFill.g+","+a.colorFill.b+",0)"),c.beginPath(),c.fillStyle=e,c.fillRect(d,
b,h,f),a.doubleside&&(e=c.createLinearGradient(d,parseInt(b)-parseInt(f),d,parseInt(b)),e.addColorStop(1,"rgba("+a.colorFill.r+","+a.colorFill.g+","+a.colorFill.b+","+parseInt(a.opacity)/100+")"),e.addColorStop(0,"rgba("+a.colorFill.r+","+a.colorFill.g+","+a.colorFill.b+",0)"),c.beginPath(),c.fillStyle=e,c.fillRect(d,parseInt(b)-parseInt(f)+2,h,f));c.restore();a._currentPosition<-a.height/4&&(a._waiting=!0,a._currentPosition=a.height+0.2*a.height);try{if(a._considerAlpha){for(var m=c.getImageData(0,
0,a.width,a.height),n=m.data,d=0;d<n.length;d+=4)0==l[d+3]&&(n[d+3]=0);c.putImageData(m,0,0)}}catch(p){}}}},1E3/a.FPS)})();return this}})(jQuery);